### PR TITLE
BUG FIX: Multipart/form-data crashed if data was missing

### PR DESCRIPTION
**Pull request by JaapWijnen**
Fix a crash in FormDataDecoderContext when the offset doesn't exist when parsing multipart form data ( vapor/vapor#2548 )

### CODE REVIEW

**Comment by JaapWijnen** [comment]
also moved over a test from vapor and removed a utility function that was unused

**Comment by siemensikkema** [comment]
@JaapWijnen in order to revive multipart-kit properly we'd also need to update the README to bump the minimum Swift version and replace the Circle CI badge with the GH Actions one. Up to you if you want to include that in this PR or if you want to keep this one purely about the bug fix.

**Comment by JaapWijnen** [comment]
I'll try to add those later today, thanks for pointing out!

**Comment by JaapWijnen** [comment]
@siemensikkema All done! :) I've also updated the tools version and macOS requirements to match all vapor packages. I assumed we want to keep these uniform across all repos to minimize maintenance :) Let me know if you'd like to see anything different!

**Review by siemensikkema — APPROVED** [review]
Looks good! Thanks for updating and the push to make this independent from Vapor 👍🏻

**Comment by tanner0101** [comment]
These changes are now available in [4.0.0-beta.2.1](https://github.com/vapor/multipart-kit/releases/tag/4.0.0-beta.2.1)

**Pull request merged**
