### PR TITLE
Optimize and simplify parser

### LINKED ISSUE #58: Explore optimizing parser
There might be some opportunities for optimizing the new parser from #54 as discussed https://github.com/vapor/multipart-kit/pull/54#issuecomment-817924731 and https://github.com/vapor/multipart-kit/pull/54#issuecomment-818236481.

### PR DESCRIPTION
**Pull request by siemensikkema**
Use more efficient parsing of multipart bodies to improve performance to near the level of the old C parser (~8% slower). Resolves #58 and replaces #59. Thanks to @edwellbrook for the initial test case and @weissi for help on parser performance 🙏🏻

### CODE REVIEW

**Comment by siemensikkema** [comment]
Performance metrics for parsing 25MB attachment:
- c parser: 0.117 s
- 4.0.1: 0.651 s
- current: 0.127 s

**Comment by siemensikkema** [comment]
Updated performance metrics using new dynamically generated test data:
- c parser: 0.062 s
- 4.0.1: 1.404 s
- current: 0.117 s

**Review by gwynne — APPROVED** [review]
LGTM

**Review by 0xTim — APPROVED** [review]
LGTM

**Pull request merged**
